name: Linux
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        service:
          - almalinux-8
          - apache-arrow
          - arch-linux
          - centos-7
          # - fedora-arm32v7-rawhide
          # - fedora-rawhide
          - ruby-2.7
          - ruby-3.0
          - ruby-3.1
          - ubuntu-18.04
          - ubuntu-20.04
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Workaround for Docker
        # https://github.com/actions/virtual-environments/issues/5490#issuecomment-1118328567
        run: |
          sudo rm /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build Docker image
        run: |
          docker-compose build ${{ matrix.service }}
      - name: Run
        run: |
          docker-compose run ${{ matrix.service }}
