name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        run: |
          ruby \
            -e 'print("## "); puts(ARGF.read.split(/^## /)[1])' \
            NEWS.md > release-note.md
          gh release create \
            ${GITHUB_REF_NAME} \
            --discussion-category Releases \
            --notes-file release-note.md \
            --title "$(head -n 1 release-note.md | sed -e 's/^## //')"
        env:
          GH_TOKEN: ${{ github.token }}
