name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Extract release note
        run: |
          ruby \
            -e 'print("## "); puts(ARGF.read.split(/^## /)[1])' \
            NEWS.md > release-note.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-note.md
          discussion_category_name: "Releases"
